//! Hand-written bindings for Dawn's C API (webgpu.h, generated by the build).
//!
//! Same approach as glfw_bindings.zig: only what we use, field order EXACT
//! like the header (extern structs = C ABI). Pinned to the commit in
//! libs/dawn.commit. Nothing outside render/ includes this (spec §7).

// ── Opaque objects ───────────────────────────────────────────────────────────
pub const WGPUInstance = *opaque {};
pub const WGPUAdapter = *opaque {};
pub const WGPUDevice = *opaque {};
pub const WGPUQueue = *opaque {};
pub const WGPUSurface = *opaque {};
pub const WGPUTexture = *opaque {};
pub const WGPUTextureView = *opaque {};
pub const WGPUBuffer = *opaque {};
pub const WGPUShaderModule = *opaque {};
pub const WGPURenderPipeline = *opaque {};
pub const WGPUBindGroup = *opaque {};
pub const WGPUBindGroupLayout = *opaque {};
pub const WGPUPipelineLayout = *opaque {};
pub const WGPUCommandEncoder = *opaque {};
pub const WGPUCommandBuffer = *opaque {};
pub const WGPURenderPassEncoder = *opaque {};

// ── Scalars ──────────────────────────────────────────────────────────────────
pub const Bool = c_uint;
pub const Flags = u64;

pub const FALSE: Bool = 0;
pub const TRUE: Bool = 1;

// ── Enums (c_uint with the header's values) ──────────────────────────────────
pub const SType_ShaderSourceWGSL: c_uint = 0x00000002;
pub const SType_SurfaceSourceXlibWindow: c_uint = 0x00000006;
pub const SType_SurfaceSourceWaylandSurface: c_uint = 0x00000007;

pub const FeatureLevel_Undefined: c_uint = 0;
pub const InstanceFeatureName_TimedWaitAny: c_uint = 1;
pub const PowerPreference_Undefined: c_uint = 0;
pub const PowerPreference_HighPerformance: c_uint = 2;
pub const BackendType_Undefined: c_uint = 0;
pub const CallbackMode_WaitAnyOnly: c_uint = 1;
pub const CallbackStatus_Success: c_uint = 1;
pub const TextureUsage_RenderAttachment: Flags = 0x10;
pub const TextureUsage_CopyDst: Flags = 0x2;
pub const VertexFormat_Float32x2: c_uint = 0x0000001D;
pub const VertexFormat_Float32x4: c_uint = 0x0000001F;
pub const VertexStepMode_Vertex: c_uint = 1;
pub const PrimitiveTopology_TriangleList: c_uint = 4;
pub const CullMode_None: c_uint = 1;
pub const FrontFace_CCW: c_uint = 1;
pub const IndexFormat_Uint16: c_uint = 1;
pub const LoadOp_Clear: c_uint = 2;
pub const StoreOp_Store: c_uint = 1;
pub const TextureFormat_BGRA8Unorm: c_uint = 0x0000001B;
pub const TextureFormat_BGRA8UnormSrgb: c_uint = 0x0000001C;
pub const PresentMode_Fifo: c_uint = 1;
pub const CompositeAlphaMode_Auto: c_uint = 0;
pub const ColorWriteMask_All: Flags = 0xF;
pub const BufferUsage_Uniform: Flags = 0x40;
pub const BufferUsage_Vertex: Flags = 0x20;
pub const BufferUsage_Index: Flags = 0x10;
pub const BufferUsage_CopyDst: Flags = 0x8;
pub const WaitStatus_Success: c_uint = 1;
pub const MapMode_None: Flags = 0;
pub const Status_Success: c_uint = 1;
pub const SurfaceGetCurrentTextureStatus_SuccessOptimal: c_uint = 1;
pub const SurfaceGetCurrentTextureStatus_SuccessSuboptimal: c_uint = 2;
pub const SurfaceGetCurrentTextureStatus_Timeout: c_uint = 3;
pub const SurfaceGetCurrentTextureStatus_Outdated: c_uint = 4;
pub const SurfaceGetCurrentTextureStatus_Lost: c_uint = 5;
pub const SurfaceGetCurrentTextureStatus_Error: c_uint = 6;
pub const RequestAdapterStatus_Success: c_uint = 1;
pub const ErrorType_NoError: c_uint = 1;

// ── Structs (EXACT header field order) ───────────────────────────────────────
pub const ChainedStruct = extern struct {
    next: ?*ChainedStruct = null,
    sType: c_uint,
};

pub const StringView = extern struct {
    data: ?[*]const u8 = null,
    length: usize = std.math.maxInt(usize), // WGPU_STRLEN

    pub fn from(s: [:0]const u8) StringView {
        return .{ .data = s.ptr, .length = s.len };
    }
};
const std = @import("std");

pub const Color = extern struct {
    r: f64 = 0,
    g: f64 = 0,
    b: f64 = 0,
    a: f64 = 0,
};

pub const Origin3D = extern struct {
    x: u32 = 0,
    y: u32 = 0,
    z: u32 = 0,
};

pub const Extent3D = extern struct {
    width: u32 = 0,
    height: u32 = 0,
    depthOrArrayLayers: u32 = 1,
};

pub const Future = extern struct {
    id: u64 = 0,
};

pub const FutureWaitInfo = extern struct {
    future: Future = .{},
    completed: Bool = FALSE,
};

pub const InstanceDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    requiredFeatureCount: usize = 0,
    requiredFeatures: ?*const c_uint = null,
    requiredLimits: ?*const anyopaque = null,
};

pub const RequestAdapterOptions = extern struct {
    nextInChain: ?*ChainedStruct = null,
    featureLevel: c_uint = FeatureLevel_Undefined,
    powerPreference: c_uint = PowerPreference_Undefined,
    forceFallbackAdapter: Bool = FALSE,
    backendType: c_uint = BackendType_Undefined,
    compatibleSurface: ?WGPUSurface = null,
};

pub const RequestAdapterCallback = ?*const fn (
    status: c_uint,
    adapter: ?WGPUAdapter,
    message: StringView,
    userdata1: ?*anyopaque,
    userdata2: ?*anyopaque,
) callconv(.c) void;

pub const RequestAdapterCallbackInfo = extern struct {
    nextInChain: ?*ChainedStruct = null,
    mode: c_uint,
    callback: RequestAdapterCallback,
    userdata1: ?*anyopaque = null,
    userdata2: ?*anyopaque = null,
};

pub const RequestDeviceStatus_Success: c_uint = 1;

pub const RequestDeviceCallback = ?*const fn (
    status: c_uint,
    device: ?WGPUDevice,
    message: StringView,
    userdata1: ?*anyopaque,
    userdata2: ?*anyopaque,
) callconv(.c) void;

pub const RequestDeviceCallbackInfo = extern struct {
    nextInChain: ?*ChainedStruct = null,
    mode: c_uint,
    callback: RequestDeviceCallback,
    userdata1: ?*anyopaque = null,
    userdata2: ?*anyopaque = null,
};

pub const UncapturedErrorCallback = ?*const fn (
    device: ?WGPUDevice,
    error_type: c_uint,
    message: StringView,
    userdata1: ?*anyopaque,
    userdata2: ?*anyopaque,
) callconv(.c) void;

pub const DeviceDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
    requiredFeatureCount: usize = 0,
    requiredFeatures: ?*const c_uint = null,
    requiredLimits: ?*const anyopaque = null,
    // defaultQueue (WGPUQueueDescriptor: nextInChain + label) inlined:
    defaultQueue_nextInChain: ?*ChainedStruct = null,
    defaultQueue_label: StringView = .{},
    // deviceLostCallbackInfo (WGPUDeviceLostCallbackInfo):
    // nextInChain + mode + callback + userdata1/2
    deviceLost_nextInChain: ?*ChainedStruct = null,
    deviceLost_mode: c_uint = 0,
    deviceLost_callback: ?*const anyopaque = null,
    deviceLost_userdata1: ?*anyopaque = null,
    deviceLost_userdata2: ?*anyopaque = null,
    // uncapturedErrorCallbackInfo (WGPUUncapturedErrorCallbackInfo — has NO
    // `mode` field, unlike deviceLost):
    // nextInChain + callback + userdata1/2
    uncaptured_nextInChain: ?*ChainedStruct = null,
    uncaptured_callback: UncapturedErrorCallback = null,
    uncaptured_userdata1: ?*anyopaque = null,
    uncaptured_userdata2: ?*anyopaque = null,
};

pub const SurfaceDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
};

pub const SurfaceSourceXlibWindow = extern struct {
    chain: ChainedStruct,
    display: *anyopaque,
    window: u64,
};

pub const SurfaceSourceWaylandSurface = extern struct {
    chain: ChainedStruct,
    display: *anyopaque,
    surface: *anyopaque,
};

pub const SurfaceConfiguration = extern struct {
    nextInChain: ?*ChainedStruct = null,
    device: WGPUDevice,
    format: c_uint,
    usage: Flags,
    width: u32,
    height: u32,
    viewFormatCount: usize = 0,
    viewFormats: ?*const c_uint = null,
    alphaMode: c_uint = CompositeAlphaMode_Auto,
    presentMode: c_uint = PresentMode_Fifo,
};

pub const SurfaceTexture = extern struct {
    nextInChain: ?*ChainedStruct = null,
    texture: ?WGPUTexture,
    status: c_uint,
};

pub const ShaderSourceWGSL = extern struct {
    chain: ChainedStruct,
    code: StringView,
};

pub const ShaderModuleDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
};

pub const BufferDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
    usage: Flags,
    size: u64,
    mappedAtCreation: Bool = FALSE,
};

pub const VertexAttribute = extern struct {
    nextInChain: ?*ChainedStruct = null,
    format: c_uint,
    offset: u64,
    shaderLocation: u32,
};

pub const VertexBufferLayout = extern struct {
    nextInChain: ?*ChainedStruct = null,
    stepMode: c_uint,
    arrayStride: u64,
    attributeCount: usize,
    attributes: [*]const VertexAttribute,
};

pub const BindGroupLayoutEntry = extern struct {
    nextInChain: ?*ChainedStruct = null,
    binding: u32,
    visibility: Flags,
    bindingArraySize: u32 = 0,
    // buffer: BufferBindingLayout { nextInChain, type, minBindingSize }
    buffer_nextInChain: ?*ChainedStruct = null,
    buffer_type: c_uint, // BufferBindingType_Uniform = 2
    buffer_minBindingSize: u64 = 0,
    // sampler / texture / storageTexture: BindingNotUsed (0) by default
    sampler_nextInChain: ?*ChainedStruct = null,
    sampler_type: c_uint = 0,
    sampler_count: u64 = 0,
    texture_nextInChain: ?*ChainedStruct = null,
    texture_sampleType: c_uint = 0,
    texture_viewDimension: c_uint = 0,
    texture_multisampled: Bool = FALSE,
    storageTexture_nextInChain: ?*ChainedStruct = null,
    storageTexture_access: c_uint = 0,
    storageTexture_format: c_uint = 0,
    storageTexture_viewDimension: c_uint = 0,
};

pub const BufferBindingType_Uniform: c_uint = 2;

pub const BindGroupLayoutDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
    entryCount: usize,
    entries: [*]const BindGroupLayoutEntry,
};

pub const PipelineLayoutDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
    bindGroupLayoutCount: usize,
    bindGroupLayouts: [*]const WGPUBindGroupLayout,
    immediateSize: u32 = 0,
};

pub const BindGroupEntry = extern struct {
    nextInChain: ?*ChainedStruct = null,
    binding: u32,
    buffer: ?WGPUBuffer,
    offset: u64,
    size: u64,
    sampler: ?*anyopaque = null,
    textureView: ?WGPUTextureView = null,
};

pub const BindGroupDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
    layout: WGPUBindGroupLayout,
    entryCount: usize,
    entries: [*]const BindGroupEntry,
};

pub const ShaderStage_Vertex: Flags = 0x1;
pub const ShaderStage_Fragment: Flags = 0x2;

pub const RenderPipelineDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
    layout: ?WGPUPipelineLayout,
    // vertex: VertexState
    vertex_nextInChain: ?*ChainedStruct = null,
    vertex_module: WGPUShaderModule,
    vertex_entryPoint: StringView = .{},
    vertex_constantCount: usize = 0,
    vertex_constants: ?*const anyopaque = null,
    vertex_bufferCount: usize,
    vertex_buffers: ?[*]const VertexBufferLayout,
    // primitive: PrimitiveState
    primitive_nextInChain: ?*ChainedStruct = null,
    primitive_topology: c_uint = PrimitiveTopology_TriangleList,
    primitive_stripIndexFormat: c_uint = 0,
    primitive_frontFace: c_uint = FrontFace_CCW,
    primitive_cullMode: c_uint = CullMode_None,
    primitive_unclippedDepth: Bool = FALSE,
    // depthStencil: nullable pointer
    depthStencil: ?*const anyopaque = null,
    // multisample: MultisampleState
    multisample_nextInChain: ?*ChainedStruct = null,
    multisample_count: u32 = 1,
    multisample_mask: u32 = 0xFFFFFFFF,
    multisample_alphaToCoverageEnabled: Bool = FALSE,
    // fragment: nullable FragmentState
    fragment: ?*const FragmentState,
};

pub const FragmentState = extern struct {
    nextInChain: ?*ChainedStruct = null,
    module: WGPUShaderModule,
    entryPoint: StringView = .{},
    constantCount: usize = 0,
    constants: ?*const anyopaque = null,
    targetCount: usize,
    targets: [*]const ColorTargetState,
};

pub const ColorTargetState = extern struct {
    nextInChain: ?*ChainedStruct = null,
    format: c_uint,
    blend: ?*const anyopaque = null,
    writeMask: Flags = ColorWriteMask_All,
};

pub const RenderPassColorAttachment = extern struct {
    nextInChain: ?*ChainedStruct = null,
    view: ?WGPUTextureView,
    depthSlice: u32 = 0xFFFFFFFF, // WGPU_DEPTH_SLICE_UNDEFINED
    resolveTarget: ?WGPUTextureView = null,
    loadOp: c_uint = LoadOp_Clear,
    storeOp: c_uint = StoreOp_Store,
    clearValue: Color = .{},
};

pub const RenderPassDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
    colorAttachmentCount: usize,
    colorAttachments: [*]const RenderPassColorAttachment,
    depthStencilAttachment: ?*const anyopaque = null,
    occlusionQuerySet: ?*anyopaque = null,
    timestampWrites: ?*const anyopaque = null,
};

pub const CommandEncoderDescriptor = extern struct {
    nextInChain: ?*ChainedStruct = null,
    label: StringView = .{},
};

// ── Functions ────────────────────────────────────────────────────────────────
pub extern fn wgpuCreateInstance(descriptor: ?*const InstanceDescriptor) ?WGPUInstance;
pub extern fn wgpuInstanceCreateSurface(instance: WGPUInstance, descriptor: *const SurfaceDescriptor) ?WGPUSurface;
pub extern fn wgpuInstanceRequestAdapter(instance: WGPUInstance, options: ?*const RequestAdapterOptions, callbackInfo: RequestAdapterCallbackInfo) Future;
pub extern fn wgpuInstanceWaitAny(instance: WGPUInstance, futureCount: usize, futures: ?[*]FutureWaitInfo, timeoutNS: u64) c_uint;
pub extern fn wgpuInstanceRelease(instance: WGPUInstance) void;

pub extern fn wgpuAdapterRequestDevice(adapter: WGPUAdapter, descriptor: ?*const DeviceDescriptor, callbackInfo: RequestDeviceCallbackInfo) Future;
pub extern fn wgpuAdapterRelease(adapter: WGPUAdapter) void;

pub extern fn wgpuDeviceGetQueue(device: WGPUDevice) ?WGPUQueue;
pub extern fn wgpuDeviceCreateCommandEncoder(device: WGPUDevice, descriptor: ?*const CommandEncoderDescriptor) ?WGPUCommandEncoder;
pub extern fn wgpuDeviceCreateShaderModule(device: WGPUDevice, descriptor: *const ShaderModuleDescriptor) ?WGPUShaderModule;
pub extern fn wgpuDeviceCreateBuffer(device: WGPUDevice, descriptor: *const BufferDescriptor) ?WGPUBuffer;
pub extern fn wgpuDeviceCreateBindGroupLayout(device: WGPUDevice, descriptor: *const BindGroupLayoutDescriptor) ?WGPUBindGroupLayout;
pub extern fn wgpuDeviceCreatePipelineLayout(device: WGPUDevice, descriptor: *const PipelineLayoutDescriptor) ?WGPUPipelineLayout;
pub extern fn wgpuDeviceCreateBindGroup(device: WGPUDevice, descriptor: *const BindGroupDescriptor) ?WGPUBindGroup;
pub extern fn wgpuDeviceCreateRenderPipeline(device: WGPUDevice, descriptor: *const RenderPipelineDescriptor) ?WGPURenderPipeline;
pub extern fn wgpuDeviceRelease(device: WGPUDevice) void;

pub extern fn wgpuQueueWriteBuffer(queue: WGPUQueue, buffer: WGPUBuffer, bufferOffset: u64, data: *const anyopaque, size: usize) void;
pub extern fn wgpuQueueSubmit(queue: WGPUQueue, commandCount: usize, commands: [*]const WGPUCommandBuffer) void;
pub extern fn wgpuQueueRelease(queue: WGPUQueue) void;

pub const SurfaceCapabilities = extern struct {
    nextInChain: ?*ChainedStruct = null,
    usages: Flags = 0,
    formatCount: usize = 0,
    formats: ?[*]const c_uint = null,
    presentModeCount: usize = 0,
    presentModes: ?[*]const c_uint = null,
    alphaModeCount: usize = 0,
    alphaModes: ?[*]const c_uint = null,
};

pub extern fn wgpuSurfaceGetCapabilities(surface: WGPUSurface, adapter: WGPUAdapter, capabilities: *SurfaceCapabilities) c_uint;
pub extern fn wgpuSurfaceCapabilitiesFreeMembers(capabilities: SurfaceCapabilities) void;
pub extern fn wgpuSurfaceConfigure(surface: WGPUSurface, config: *const SurfaceConfiguration) void;
pub extern fn wgpuSurfaceGetCurrentTexture(surface: WGPUSurface, surfaceTexture: *SurfaceTexture) void;
pub extern fn wgpuSurfacePresent(surface: WGPUSurface) c_uint;
pub extern fn wgpuSurfaceUnconfigure(surface: WGPUSurface) void;
pub extern fn wgpuSurfaceRelease(surface: WGPUSurface) void;

pub extern fn wgpuTextureCreateView(texture: WGPUTexture, descriptor: ?*const anyopaque) ?WGPUTextureView;
pub extern fn wgpuTextureRelease(texture: WGPUTexture) void;
pub extern fn wgpuTextureGetFormat(texture: WGPUTexture) c_uint;

pub extern fn wgpuCommandEncoderBeginRenderPass(encoder: WGPUCommandEncoder, descriptor: *const RenderPassDescriptor) ?WGPURenderPassEncoder;
pub extern fn wgpuCommandEncoderFinish(encoder: WGPUCommandEncoder, descriptor: ?*const anyopaque) ?WGPUCommandBuffer;
pub extern fn wgpuCommandEncoderRelease(encoder: WGPUCommandEncoder) void;

pub extern fn wgpuRenderPassEncoderSetPipeline(encoder: WGPURenderPassEncoder, pipeline: WGPURenderPipeline) void;
pub extern fn wgpuRenderPassEncoderSetBindGroup(encoder: WGPURenderPassEncoder, groupIndex: u32, group: ?WGPUBindGroup, dynamicOffsetCount: usize, dynamicOffsets: ?*const u32) void;
pub extern fn wgpuRenderPassEncoderSetVertexBuffer(encoder: WGPURenderPassEncoder, slot: u32, buffer: ?WGPUBuffer, offset: u64, size: u64) void;
pub extern fn wgpuRenderPassEncoderSetIndexBuffer(encoder: WGPURenderPassEncoder, buffer: ?WGPUBuffer, format: c_uint, offset: u64, size: u64) void;
pub extern fn wgpuRenderPassEncoderDrawIndexed(encoder: WGPURenderPassEncoder, indexCount: u32, instanceCount: u32, firstIndex: u32, baseVertex: i32, firstInstance: u32) void;
pub extern fn wgpuRenderPassEncoderEnd(encoder: WGPURenderPassEncoder) void;
pub extern fn wgpuRenderPassEncoderRelease(encoder: WGPURenderPassEncoder) void;

pub extern fn wgpuRenderPipelineRelease(pipeline: WGPURenderPipeline) void;
pub extern fn wgpuBindGroupRelease(group: WGPUBindGroup) void;
pub extern fn wgpuBindGroupLayoutRelease(layout: WGPUBindGroupLayout) void;
pub extern fn wgpuPipelineLayoutRelease(layout: WGPUPipelineLayout) void;
pub extern fn wgpuShaderModuleRelease(module: WGPUShaderModule) void;
pub extern fn wgpuBufferRelease(buffer: WGPUBuffer) void;
pub extern fn wgpuCommandBufferRelease(buffer: WGPUCommandBuffer) void;
pub extern fn wgpuTextureViewRelease(view: WGPUTextureView) void;
